export default {
	"erebus": "Erebus framework",
	"dialog.title.success": "Success",
	"dialog.title.info": "Information",
	"dialog.title.warn": "Attention",
	"dialog.title.error": "Error",
	"dialog.title.confirm": "Confirmation",
	"toast.title.success": "Success",
	"toast.title.info": "Information",
	"toast.title.warn": "Attention",
	"toast.title.error": "Error",
	"button.close": "Close",
	"button.yes": "Yes",
	"button.no": "No",
	"validation.pill.required": "Required",
	"validation.pill.min": "Min value is @@",
	"validation.pill.max": "Max value is @@",
	"validation.param.@today": "today",
};
